Fix NoClassDefFoundError during rendering.
Bug: http://b.android.com/180719
Change-Id: I20fad7a231db194596e8b3750787a6da9a287f02
(cherry picked from commit 50ec9d928f6883f339eca496ebeed169cfe26f0c)