IDEA-CR-54485: IDEA-221306: [Android] Designer attributes not working on JRE 11
On Linux/MacOS CustomComboBox#setUI method fails with NoClassDefFoundError: com/sun/../WindowsComboBoxUI because this class does not exist in JRE11 on linux/mac. On Windows this class exists, but check (ui instanceof WindowsComboBoxUI) evaluates false because ui will be of type WinIntelliJComboBoxUI.

Conclusion: ui may not be of type WindowsComboBoxUI
(cherry picked from commit fd61da095c0acd1ea466c0124887272f52e2b7cd)

GitOrigin-RevId: f3558abf83e7d5c94fe130044db1e0ac915dcc56