Make MergedManifest gracefully handle dispose modules
Calling MergedManifest.get(module) on a dispose module would
result in errors. This CL makes the lookup method handle
disposed module lookup calls gracefully.

Test: This CL fixes intermittent UI test failures such as
NewActivityTest#createActivityWithNonDefaultPackage which
would fail with

java.lang.Error: Already disposed: Module: 'app'
at com.android.tools.idea.tests.gui.framework.GuiTests.fatalErrorsFromIde(GuiTests.java:117)
at com.android.tools.idea.tests.gui.framework.GuiTestRule.tearDown(GuiTestRule.java:189)
at com.android.tools.idea.tests.gui.framework.GuiTestRule.access$300(GuiTestRule.java:67)
at com.android.tools.idea.tests.gui.framework.GuiTestRule$IdeHandling$1.evaluate(GuiTestRule.java:131)
Caused by: java.lang.AssertionError: Already disposed: Module: 'app'
at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:166)
at com.android.tools.idea.model.MergedManifest.get(MergedManifest.java:97)
at com.android.tools.idea.model.MergedManifest.get(MergedManifest.java:110)

Change-Id: I651b9a60df66715fa9b98abc8f660acd9eb17eca