Revert "Fixing broken build due to a typo."
Getting at runtime:
org.gradle.tooling.model.UnsupportedMethodException: Method public abstract java.io.File com.android.builder.model.AndroidBundle.getFolder() not found

This reverts commit 11ef0e0ff4dbfa6bddab8036b1101b7ad1180f06.

Change-Id: I0bf1b4fbe9005c3e57d313a0b4df2e0df4e0e27d