Fix for unit test (report from Jenkins):
Failed

com.android.tools.idea.editors.navigation.model.MasterDetailTest.testTransitionDerivationForTabletInLandscape (from com.intellij.AllTests)

Failing for the past 17 builds (Since Unstable#225 )
Took 0.15 sec.
Error Message

expected:<1> but was:<2>
Stacktrace

junit.framework.AssertionFailedError: expected:<1> but was:<2>
	at com.android.tools.idea.editors.navigation.model.NavigationEditorTest.assertDerivationCounts(NavigationEditorTest.java:57)
	at com.android.tools.idea.editors.navigation.model.MasterDetailTest.testTransitionDerivationForTabletInLandscape(MasterDetailTest.java:31)
	at com.intellij.testFramework.UsefulTestCase.access$001(UsefulTestCase.java:80)
	at com.intellij.testFramework.UsefulTestCase$2.run(UsefulTestCase.java:303)
	at com.intellij.util.ui.UIUtil.invokeAndWaitIfNeeded(UIUtil.java:2074)
	at com.intellij.testFramework.UsefulTestCase.invokeTestRunnable(UsefulTestCase.java:335)
	at com.intellij.testFramework.UsefulTestCase.runTest(UsefulTestCase.java:319)
	at com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:340)
	at com.intellij.testFramework.UsefulTestCase$3.run(UsefulTestCase.java:353)

Fix:

We now eliminate states defined by a resource file whose top element is (probably) a "Layout" class and that has no children.
The new result is correct. Change the test.

Change-Id: Ia60f79dd4b6b3652a702fc59b315d7b60e7ed497