Catch Throwable in parseDesignInfoList(ViewInfo)
We were throwing a NoClassDefFoundError in parseDesignInfoList(ViewInfo)
but that was not being handled appropriately, since the catch clauses
within this method were catching Exception, while NoClassDefFoundError
is an Error. We should catch a Throwable to be able to catch Errors as
well.

Fixes: 206038259
Test: N/A
Change-Id: I6924e3117611ecafa0075462fc008c9b87b00061