IDEA-267497 Android: "Convert to WebP" action fails with NoClassDefFoundError
Move registration of android-webp actions to separate XML and make it an optional dependency of android-plugin.xml. Now android-webp actions are only available if intellij.webp plugin is enabled.

GitOrigin-RevId: cfeda62e2e288f85a453033213a4cd3c8fb9fa88